### ISSUE TITLE
The bot should understand emoticons 

### ISSUE THREAD

**Issue by souradeepbasu** [Theo-/virtual-real-estate#15]
For example 😊 = yes and 😔= no. We need another classifier that we can train to classify emoticons. This can be pre built

**Comment by tardycorgi9917** [comment]
Can't we just add them to the entities in api.ai?

**Comment by souradeepbasu** [comment]
I guess that would work too

**Comment by Theo-** [comment]
Yeah, you can add them to the @Positive and @Negative entities.

Ex:
<img width="472" alt="screen shot 2017-01-31 at 8 48 37 am" src="https://cloud.githubusercontent.com/assets/7581961/22467305/1570e136-e792-11e6-9ea8-e075b715803f.png">
